export const availableLanguages = [
    "6502 Assembly",
    "ABAP",
    "ABNF",
    "ActionScript",
    "Ada",
    "Agda",
    "AL",
    "ANTLR4",
    "Apache Configuration",
    "Apex",
    "APL",
    "AppleScript",
    "AQL",
    "Arduino",
    "ARFF",
    "ARM Assembly",
    "Arturo",
    "AsciiDoc",
    "ASP.NET (C#)",
    "Atmel AVR Assembly",
    "AutoHotkey",
    "AutoIt",
    "AviSynth",
    "Avro IDL",
    "AWK",
    "Bash",
    "BASIC",
    "Batch",
    "BBcode",
    "BBj",
    "Bicep",
    "Birb",
    "Bison",
    "BNF",
    "BQN",
    "BrightScript",
    "Bro",
    "BSL (1C:Enterprise)",
    "C",
    "C#",
    "C++",
    "C-like",
    "CFScript",
    "ChaiScript",
    "CIL",
    "Cilk/C",
    "Cilk/C++",
    "Clojure",
    "CMake",
    "COBOL",
    "CoffeeScript",
    "Concurnas",
    "Content-Security-Policy",
    "Cooklang",
    "Coq",
    "Crystal",
    "CSS",
    "CSS Extras",
    "CSV",
    "CUE",
    "Cypher",
    "D",
    "Dart",
    "DataWeave",
    "DAX",
    "Dhall",
    "Diff",
    "Django/Jinja2",
    "DNS zone file",
    "Docker",
    "DOT (Graphviz)",
    "EBNF",
    "EditorConfig",
    "Eiffel",
    "EJS",
    "Elixir",
    "Elm",
    "Embedded Lua templating",
    "ERB",
    "Erlang",
    "Excel Formula",
    "F#",
    "Factor",
    "False",
    "Firestore security rules",
    "Flow",
    "Fortran",
    "FreeMarker Template Language",
    "GameMaker Language",
    "GAP (CAS)",
    "G-code",
    "GDScript",
    "GEDCOM",
    "gettext",
    "Gherkin",
    "Git",
    "GLSL",
    "GN",
    "GNU Linker Script",
    "Go",
    "Go module",
    "Gradle",
    "GraphQL",
    "Groovy",
    "Haml",
    "Handlebars",
    "Haskell",
    "Haxe",
    "HCL",
    "HLSL",
    "Hoon",
    "HTTP",
    "HTTP Public-Key-Pins",
    "HTTP Strict-Transport-Security",
    "IchigoJam",
    "Icon",
    "ICU Message Format",
    "Idris",
    ".ignore",
    "Inform 7",
    "Ini",
    "Io",
    "J",
    "Java",
    "JavaDoc",
    "JavaDoc-like",
    "JavaScript",
    "Java stack trace",
    "Jexl",
    "Jolie",
    "JQ",
    "JSDoc",
    "JS Extras",
    "JSON",
    "JSON5",
    "JSONP",
    "JS stack trace",
    "JS Templates",
    "Julia",
    "Keepalived Configure",
    "Keyman",
    "Kotlin",
    "KuMir (КуМир)",
    "Kusto",
    "LaTeX",
    "Latte",
    "Less",
    "LilyPond",
    "Liquid",
    "Lisp",
    "LiveScript",
    "LLVM IR",
    "Log file",
    "LOLCODE",
    "Lua",
    "Magma (CAS)",
    "Makefile",
    "Markdown",
    "Markup",
    "Markup templating",
    "Mata",
    "MATLAB",
    "MAXScript",
    "MEL",
    "Mermaid",
    "METAFONT",
    "Mizar",
    "MongoDB",
    "Monkey",
    "MoonScript",
    "N1QL",
    "N4JS",
    "Nand To Tetris HDL",
    "Naninovel Script",
    "NASM",
    "NEON",
    "Nevod",
    "nginx",
    "Nim",
    "Nix",
    "NSIS",
    "Objective-C",
    "OCaml",
    "Odin",
    "OpenCL",
    "OpenQasm",
    "Oz",
    "PARI/GP",
    "Parser",
    "Pascal",
    "Pascaligo",
    "PATROL Scripting Language",
    "PC-Axis",
    "PeopleCode",
    "Perl",
    "PHP",
    "PHPDoc",
    "PHP Extras",
    "PlantUML",
    "PL/SQL",
    "PowerQuery",
    "PowerShell",
    "Processing",
    "Prolog",
    "PromQL",
    ".properties",
    "Protocol Buffers",
    "Pug",
    "Puppet",
    "Pure",
    "PureBasic",
    "PureScript",
    "Python",
    "Q",
    "Q#",
    "QML",
    "Qore",
    "R",
    "Racket",
    "Razor C#",
    "React JSX",
    "React TSX",
    "Reason",
    "Regex",
    "Rego",
    "Ren'py",
    "ReScript",
    "reST (reStructuredText)",
    "Rip",
    "Roboconf",
    "Robot Framework",
    "Ruby",
    "Rust",
    "SAS",
    "Sass (Sass)",
    "Sass (SCSS)",
    "Scala",
    "Scheme",
    "Shell session",
    "Smali",
    "Smalltalk",
    "Smarty",
    "SML",
    "Solidity (Ethereum)",
    "Solution file",
    "Soy (Closure Template)",
    "SPARQL",
    "Splunk SPL",
    "SQF: Status Quo Function (Arma 3)",
    "SQL",
    "Squirrel",
    "Stan",
    "Stata Ado",
    "Structured Text (IEC 61131-3)",
    "Stylus",
    "SuperCollider",
    "Swift",
    "Systemd configuration file",
    "T4 templating",
    "T4 Text Templates (C#)",
    "T4 Text Templates (VB)",
    "TAP",
    "Tcl",
    "Template Toolkit 2",
    "Textile",
    "TOML",
    "Tremor",
    "Turtle",
    "Twig",
    "TypeScript",
    "TypoScript",
    "UnrealScript",
    "UO Razor Script",
    "URI",
    "V",
    "Vala",
    "VB.Net",
    "Velocity",
    "Verilog",
    "VHDL",
    "vim",
    "Visual Basic",
    "WarpScript",
    "WebAssembly",
    "Web IDL",
    "WGSL",
    "Wiki markup",
    "Wolfram language",
    "Wren",
    "Xeora",
    "XML doc (.net)",
    "Xojo (REALbasic)",
    "XQuery",
    "YAML",
    "YANG",
    "Zig",
  ];