export const languageMap: { [key: string]: string } = {
    markup: "markup",
    css: "css",
    "c-like": "clike",
    javascript: "javascript",
    abap: "abap",
    abnf: "abnf",
    actionscript: "actionscript",
    ada: "ada",
    agda: "agda",
    al: "al",
    antlr4: "antlr4",
    "apache configuration": "apacheconf",
    apex: "apex",
    apl: "apl",
    applescript: "applescript",
    aql: "aql",
    arduino: "arduino",
    arff: "arff",
    "arm assembly": "armasm",
    arturo: "arturo",
    asciidoc: "asciidoc",
    "asp.net (c#)": "aspnet",
    "6502 assembly": "asm6502",
    "atmel avr assembly": "asmatmel",
    autohotkey: "autohotkey",
    autoit: "autoit",
    avisynth: "avisynth",
    "avro idl": "avro-idl",
    awk: "awk",
    bash: "bash",
    basic: "basic",
    batch: "batch",
    bbcode: "bbcode",
    bbj: "bbj",
    bicep: "bicep",
    birb: "birb",
    bison: "bison",
    bnf: "bnf",
    bqn: "bqn",
    brightscript: "brightscript",
    bro: "bro",
    "bsl (1c:enterprise)": "bsl",
    c: "c",
    "c#": "csharp",
    "c++": "cpp",
    cfscript: "cfscript",
    chaiscript: "chaiscript",
    cil: "cil",
    "cilk/c": "cilkc",
    "cilk/c++": "cilkcpp",
    clojure: "clojure",
    cmake: "cmake",
    cobol: "cobol",
    coffeescript: "coffeescript",
    concurnas: "concurnas",
    "content-security-policy": "csp",
    cooklang: "cooklang",
    coq: "coq",
    crystal: "crystal",
    "css extras": "css-extras",
    csv: "csv",
    cue: "cue",
    cypher: "cypher",
    d: "d",
    dart: "dart",
    dataweave: "dataweave",
    dax: "dax",
    dhall: "dhall",
    diff: "diff",
    "django/jinja2": "django",
    "dns zone file": "dns-zone-file",
    docker: "docker",
    "dot (graphviz)": "dot",
    ebnf: "ebnf",
    editorconfig: "editorconfig",
    eiffel: "eiffel",
    ejs: "ejs",
    elixir: "elixir",
    elm: "elm",
    "embedded lua templating": "etlua",
    erb: "erb",
    erlang: "erlang",
    "excel formula": "excel-formula",
    "f#": "fsharp",
    factor: "factor",
    false: "false",
    "firestore security rules": "firestore-security-rules",
    flow: "flow",
    fortran: "fortran",
    "freemarker template language": "ftl",
    "gamemaker language": "gml",
    "gap (cas)": "gap",
    "g-code": "gcode",
    gdscript: "gdscript",
    gedcom: "gedcom",
    gettext: "gettext",
    gherkin: "gherkin",
    git: "git",
    glsl: "glsl",
    gn: "gn",
    "gnu linker script": "linker-script",
    go: "go",
    "go module": "go-module",
    gradle: "gradle",
    graphql: "graphql",
    groovy: "groovy",
    haml: "haml",
    handlebars: "handlebars",
    haskell: "haskell",
    haxe: "haxe",
    hcl: "hcl",
    hlsl: "hlsl",
    hoon: "hoon",
    http: "http",
    "http public-key-pins": "hpkp",
    "http strict-transport-security": "hsts",
    ichigojam: "ichigojam",
    icon: "icon",
    "icu message format": "icu-message-format",
    idris: "idris",
    ".ignore": "ignore",
    "inform 7": "inform7",
    ini: "ini",
    io: "io",
    j: "j",
    java: "java",
    javadoc: "javadoc",
    "javadoc-like": "javadoclike",
    "java stack trace": "javastacktrace",
    jexl: "jexl",
    jolie: "jolie",
    jq: "jq",
    jsdoc: "jsdoc",
    "js extras": "js-extras",
    json: "json",
    json5: "json5",
    jsonp: "jsonp",
    "js stack trace": "jsstacktrace",
    "js templates": "js-templates",
    julia: "julia",
    "keepalived configure": "keepalived",
    keyman: "keyman",
    kotlin: "kotlin",
    "kumir (кумир)": "kumir",
    kusto: "kusto",
    latex: "latex",
    latte: "latte",
    less: "less",
    lilypond: "lilypond",
    liquid: "liquid",
    lisp: "lisp",
    livescript: "livescript",
    "llvm ir": "llvm",
    "log file": "log",
    lolcode: "lolcode",
    lua: "lua",
    "magma (cas)": "magma",
    makefile: "makefile",
    markdown: "markdown",
    "markup templating": "markup-templating",
    mata: "mata",
    matlab: "matlab",
    maxscript: "maxscript",
    mel: "mel",
    mermaid: "mermaid",
    metafont: "metafont",
    mizar: "mizar",
    mongodb: "mongodb",
    monkey: "monkey",
    moonscript: "moonscript",
    n1ql: "n1ql",
    n4js: "n4js",
    "nand to tetris hdl": "nand2tetris-hdl",
    "naninovel script": "naniscript",
    nasm: "nasm",
    neon: "neon",
    nevod: "nevod",
    nginx: "nginx",
    nim: "nim",
    nix: "nix",
    nsis: "nsis",
    "objective-c": "objectivec",
    ocaml: "ocaml",
    odin: "odin",
    opencl: "opencl",
    openqasm: "openqasm",
    oz: "oz",
    "pari/gp": "parigp",
    parser: "parser",
    pascal: "pascal",
    pascaligo: "pascaligo",
    "patrol scripting language": "psl",
    "pc-axis": "pcaxis",
    peoplecode: "peoplecode",
    perl: "perl",
    php: "php",
    phpdoc: "phpdoc",
    "php extras": "php-extras",
    plantuml: "plant-uml",
    "pl/sql": "plsql",
    powerquery: "powerquery",
    powershell: "powershell",
    processing: "processing",
    prolog: "prolog",
    promql: "promql",
    ".properties": "properties",
    "protocol buffers": "protobuf",
    pug: "pug",
    puppet: "puppet",
    pure: "pure",
    purebasic: "purebasic",
    purescript: "purescript",
    python: "python",
    "q#": "qsharp",
    "q (kdb+ database)": "q",
    qml: "qml",
    qore: "qore",
    r: "r",
    racket: "racket",
    "razor c#": "cshtml",
    "react jsx": "jsx",
    "react tsx": "tsx",
    reason: "reason",
    regex: "regex",
    rego: "rego",
    "ren'py": "renpy",
    rescript: "rescript",
    "rest (restructuredtext)": "rest",
    rip: "rip",
    roboconf: "roboconf",
    "robot framework": "robotframework",
    ruby: "ruby",
    rust: "rust",
    sas: "sas",
    "sass (sass)": "sass",
    "sass (scss)": "scss",
    scala: "scala",
    scheme: "scheme",
    "shell session": "shell-session",
    smali: "smali",
    smalltalk: "smalltalk",
    smarty: "smarty",
    sml: "sml",
    "solidity (ethereum)": "solidity",
    "solution file": "solution-file",
    "soy (closure template)": "soy",
    sparql: "sparql",
    "splunk spl": "splunk-spl",
    "sqf: status quo function (arma 3)": "sqf",
    sql: "sql",
    squirrel: "squirrel",
    stan: "stan",
    "stata ado": "stata",
    "structured text (iec 61131-3)": "iecst",
    stylus: "stylus",
    supercollider: "supercollider",
    swift: "swift",
    "systemd configuration file": "systemd",
    "t4 templating": "t4-templating",
    "t4 text templates (c#)": "t4-cs",
    "t4 text templates (vb)": "t4-vb",
    tap: "tap",
    tcl: "tcl",
    "template toolkit 2": "tt2",
    textile: "textile",
    toml: "toml",
    tremor: "tremor",
    turtle: "turtle",
    twig: "twig",
    typescript: "typescript",
    typoscript: "typoscript",
    unrealscript: "unrealscript",
    "uo razor script": "uorazor",
    uri: "uri",
    v: "v",
    vala: "vala",
    "vb.net": "vbnet",
    velocity: "velocity",
    verilog: "verilog",
    vhdl: "vhdl",
    vim: "vim",
    "visual basic": "visual-basic",
    warpscript: "warpscript",
    webassembly: "wasm",
    "web idl": "web-idl",
    wgsl: "wgsl",
    "wiki markup": "wiki",
    "wolfram language": "wolfram",
    wren: "wren",
    xeora: "xeora",
    "xml doc (.net)": "xml-doc",
    "xojo (realbasic)": "xojo",
    xquery: "xquery",
    yaml: "yaml",
    yang: "yang",
    zig: "zig",
};